Repository Nikhil-2002/Programming_Hactoberfest23, pull requests merged in 2023-10, with the labels that each got.

#12 Create largestelement.c
  largestelement.c
Labels: Hactoberfest2023, hactoberfest-accepted

#11 Create shell_sort.cpp
  shell_sort/shell_sort.cpp
Labels: Hactoberfest2023, hactoberfest-accepted

#13 Added Program To Find Smallest Element in an Array
  find_the_smallest_element_in_an_array/Solution.java
Labels: hactoberfest-accepted

#14 countingevenodd.c
  countingevenodd.c
Labels: hactoberfest-accepted

#16 issue resolved of removing duplicates from an array
  removingDuplicates/removeDupFromArray.cpp
Labels: hactoberfest-accepted

#17 Issue resolved of finding that arrays are disjoint or not
  .vscode/settings.json
  findDisjoint/disjointOrNot.cpp
Labels: hactoberfest-accepted

#18 Calculate the sum of elements in an array
  array_sum.cpp
Labels: hactoberfest23, hactoberfest-accepted

#21 Issue#4_reverseAnArrayAdded
  Reverse_an_array/Reverse_an_array.cpp
  Reverse_an_array/Reverse_an_array.exe
Labels: hactoberfest, hactoberfest-accepted

#20 Create finding_repeating_elements.c
  finding_repeating_elements.c
Labels: hactoberfest, hactoberfest-accepted

#22 Revert "Finding the Longest Palindrome in an Array"
  Finding_the_Longest_Palindrome_in_Array/Solution.java
Labels: hactoberfest, hactoberfest-accepted

#23 Longest palindrome subsequence length
  longest_palindrome_subsequence_length/Solution.java
Labels: hactoberfest, hactoberfest-accepted

#28 Create turtle.py
  turtle.py
Labels: hactoberfest-accepted

#27 factorial in c.C
  factorial.c
Labels: hactoberfest-accepted

#32 Create Reverse_Array.java
  Reverse_an_array/Reverse_Array.java
Labels: hactoberfest, hactoberfest-accepted

#31 Create reverse_an_array.c @hactoberfest
  reverse_an_array.c
Labels: hactoberfest, hactoberfest-accepted

#29 Add files via upload
  BubbleSort.java
  InsertionSort.java
  Knapsack.py
Labels: hactoberfest, hactoberfest-accepted

#45 Added Java Program to Sort Elements of an Array
  sort_elements_of_array/Solution.java
Labels: hactoberfest-accepted

#44 Added Java Program To Count Even and Odd Numbers
  count_number_of_odd_even_elements/Solution.java
Labels: hactoberfest-accepted

#43 program which contain so many operation on bits (BIT MAINPULATION)
  BIT_MANIPULATION.cpp
Labels: hactoberfest-accepted

#42 Merge sort with better time complexity
  MergeSort/MergeSort.java
Labels: hactoberfest-accepted

#41 added oddEvenCount in javaScript
  count_Even_Odd/countEvenOdd.js
Labels: hactoberfest-accepted

#40 Create BinarySearch.cpp
  BinarySearch.cpp
Labels: hactoberfest-accepted

#39 Create Count_number_of_subarray_having_given_xor.cpp
  Count_number_of_subarray_having_given_xor.cpp
Labels: hactoberfest-accepted

#38 Added_count_frequency_of_array_items.cpp
  count_frequency_of_array_items.cpp
Labels: hactoberfest-accepted

#35 Kadane's algorithm
  Kadane's algorithm
Labels: hactoberfest-accepted

#34 binary search added
  binarySearch.cpp
Labels: hactoberfest-accepted

#33 Fixed- Added DSU and Trie Data Structure
  Disjoint Set Union/DisjointSetUnion.cpp
  Trie/Trie.cpp
Labels: hactoberfest-accepted

#49 Create To check if two arrays are disjoint or not
  To check if two arrays are disjoint or not
Labels: hactoberfest-accepted

#48 Create To find all repeating elements in an array.
  To find all repeating elements in an array.
Labels: hactoberfest-accepted

#47 Create To find longest palindrome in a array
  To find longest palindrome in a array
Labels: hactoberfest-accepted

#46 Create smallest element in array.c
  smallest element in array.c
Labels: hactoberfest-accepted

#50 Create Pairwise swap elements of a linked list
  Pairwise swap elements of a linked list
Labels: hactoberfest, hactoberfest-accepted

#53 Create searchInRotArray.java
  searchInRotArray.java
Labels: hactoberfest, hactoberfest-accepted

#52 Create KahnsAlgo.cpp
  KahnsAlgo.cpp
Labels: hactoberfest, hactoberfest-accepted

#57 Create if a number is an Armstrong Number
  if a number is an Armstrong Number.java
Labels: hactoberfest, hactoberfest-accepted

#55 Create Pigeonhole Sort
  Pigeonhole Sort
Labels: hactoberfest, hactoberfest-accepted

#54 Longest Palindrome in Array
  longest_palindrome_in_array
Labels: hactoberfest, hactoberfest-accepted

#67 Added PalindromeChecker.java
  PalindromeChecker.java
Labels: hactoberfest, hactoberfest-accepted

#74 Create smallestelementusingScanner.java
  find_the_smallest_element_in_an_array/smallestelementusingScanner.java
Labels: hactoberfest, hactoberfest-accepted

#73 Create ReverseArrayUsingScanner.java
  Reverse_an_array/ReverseArrayUsingScanner.java
Labels: hactoberfest, hactoberfest-accepted

#72 Create EvenOddinArray.java
  EvenOddinArray.java
Labels: hactoberfest, hactoberfest-accepted

#60 Create rotate_array_right.cpp
  rotate.cpp
Labels: hactoberfest, hactoberfest-accepted

#61 Create Count_Even_and_Odd_In_Array.cpp
  CheckEvenandOddInArray.cpp
Labels: hactoberfest, hactoberfest-accepted

#62 added C scripts of Dynamic Programming
  Greedy_Knapsack.c
  LCS.c
  SCS.c
Labels: hactoberfest, hactoberfest-accepted

#63 Create quickSort.cpp
  quickSort.cpp
Labels: hactoberfest, hactoberfest-accepted

#64 palindrome checker
  .vscode/settings.json
  BIT_MANIPULATION.cpp
  BinarySearch.cpp
  BubbleSort.java
  CONTRIBUTING.md
  Count_number_of_subarray_having_given_xor.cpp
  Disjoint Set Union/DisjointSetUnion.cpp
  InsertionSort.java
  Kadane's Algorithm.cpp
  Kadane's algorithm
  KahnsAlgo.cpp
  Knapsack.py
  MergeSort/MergeSort.java
  Pairwise swap elements of a linked list
  Pigeonhole Sort
  README.md
  Reverse_an_array/Reverse_Array.java
  Reverse_an_array/Reverse_an_array.cpp
  Reverse_an_array/Reverse_an_array.exe
  To check if two arrays are disjoint or not
  To find all repeating elements in an array.
  To find longest palindrome in a array
  Trie/Trie.cpp
  array_sum.cpp
  binarySearch.cpp
  count_Even_Odd/countEvenOdd.class
  count_Even_Odd/countEvenOdd.cpp
  count_Even_Odd/countEvenOdd.exe
  count_Even_Odd/countEvenOdd.java
  count_Even_Odd/countEvenOdd.js
  count_Even_Odd/countEvenOdd.py
  count_frequency_of_array_items.cpp
  count_number_of_odd_even_elements/Solution.java
  countingevenodd.c
  factorial.c
  findDisjoint/disjointOrNot.cpp
  find_the_smallest_element_in_an_array/Solution.java
  finding_repeating_elements.c
  if a number is an Armstrong Number.java
  largestelement.c
  longest_palindrome_in_array
  longest_palindrome_subsequence_length/Solution.java
  palindrome.cpp
  removingDuplicates/removeDupFromArray.cpp
  reverse_an_array.c
  rotateimage.cpp
  searchInRotArray.java
  shell_sort/shell_sort.cpp
  smallest element in array.c
  sort_elements_of_array/Solution.java
  turtle.py
Labels: duplicate, hactoberfest, hactoberfest-accepted

#69 Created soln.cpp for issue #9
  count_number_of_odd_even_elements/soln.cpp
Labels: hactoberfest, hactoberfest-accepted

#80 added evaluate postfix exp
  postfix_eval/eval_postfix.c
Labels: hactoberfest, hactoberfest-accepted

#91 Created a Merge Sort Program in C
  mergesort.cpp
Labels: hactoberfest, hactoberfest-accepted

#70 Create Palindrom_checkerwithJava.java
  Palindrom_checkerwithJava.java
Labels: hactoberfest, hactoberfest-accepted

#71 Create ArrayDisjoinOrNot.java
  findDisjoint/ArrayDisjoinOrNot.java
Labels: hactoberfest, hactoberfest-accepted

#76 Create Minimum Sum of Four Digit Number After Splitting Digits
  2160. Minimum Sum of Four Digit Number After Splitting Digits
Labels: hactoberfest, hactoberfest-accepted

#77 Create Palindrome_Num_Checker.cpp
  Palindrome_Num_Checker.cpp
Labels: hactoberfest, hactoberfest-accepted

#78 Update palindrome.cpp
  palindrome.cpp
Labels: hactoberfest, hactoberfest-accepted

#79 added kadans algorithm and unique element in array code in cpp
  FindUniqueElement.cpp
  KadansAlgorithm.cpp
Labels: hactoberfest, hactoberfest-accepted

#81 greatest element in array
  Gr8stIntInArr.cpp
Labels: hactoberfest, hactoberfest-accepted

#82 added bfs code
  BFS.cpp
Labels: hactoberfest, hactoberfest-accepted

#83 Create NGE.java
  NGE.java
Labels: hactoberfest, hactoberfest-accepted

#87 added pattern program
  patterns/.DS_Store
  patterns/starPatterns/Pattern0.java
  patterns/starPatterns/Pattern1.java
  patterns/starPatterns/Pattern10.java
  patterns/starPatterns/Pattern11.java
  patterns/starPatterns/Pattern12.java
  patterns/starPatterns/Pattern13.java
  patterns/starPatterns/Pattern14.java
  patterns/starPatterns/Pattern15.java
  patterns/starPatterns/Pattern16.java
  patterns/starPatterns/Pattern17.java
  patterns/starPatterns/Pattern18.java
  patterns/starPatterns/Pattern19.java
  patterns/starPatterns/Pattern2.java
  patterns/starPatterns/Pattern20.java
  patterns/starPatterns/Pattern21.java
  patterns/starPatterns/Pattern22.java
  patterns/starPatterns/Pattern3.java
  patterns/starPatterns/Pattern4.java
  patterns/starPatterns/Pattern5.java
  patterns/starPatterns/Pattern6.java
  patterns/starPatterns/Pattern7.java
  patterns/starPatterns/Pattern8.java
  patterns/starPatterns/Pattern9.java
Labels: hactoberfest, hactoberfest-accepted

#101 Create-take-input-in-string-form-and-convert-to-array-format-for-operation #98
  Take input in String form and convert to array format for operation #98
Labels: hactoberfest-accepted
